name: inninglog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  amplitude_flutter: 4.3.4
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

  table_calendar: ^3.0.9

  url_launcher: ^6.2.5


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  image_picker: ^1.1.2
  go_router: ^13.0.0
  kakao_flutter_sdk_user: ^1.4.1
  collection: ^1.17.1
  month_picker_dialog: ^6.0.3
  http: ^1.4.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_dotenv: ^5.2.1





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0



flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
    - assets/images/onboard_1.jpg
    - assets/images/onboard_2.jpg
    - assets/images/onboard_3.jpg
    - assets/images/onboard_4.jpg



  fonts:
    - family: MBC1961GulimOTF
      fonts:
        - asset: assets/fonts/MBC1961GulimOTF.ttf

    - family: Pretendard
      fonts:
         - asset: assets/fonts/Pretendard-Regular.otf
         - asset: assets/fonts/Pretendard-Bold.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf
    - family: omyu pretty
      fonts:
        - asset: assets/fonts/omyu pretty.ttf


