name: inninglog
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter

  table_calendar: ^3.0.9


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/KakaoTalk_20250611_184301449.jpg
    - assets/images/KakaoTalk_20250611_184301449_01.jpg
    - assets/images/KakaoTalk_20250611_184301449_03.jpg
    - assets/images/KakaoTalk_20250611_184301449_04.jpg
    - assets/images/KakaoTalk_20250611_184301449_05.jpg
    - assets/images/KakaoTalk_20250611_184301449_06.jpg
    - assets/icons/splash_green.svg
    - assets/icons/splash_white.svg

  fonts:
    - family: MBC1961GulimOTF
      fonts:
        - asset: assets/fonts/MBC1961GulimOTF.ttf

    - family: Pretendard
      fonts:
         - asset: assets/fonts/Pretendard-Regular.otf
         - asset: assets/fonts/Pretendard-Bold.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/InterRegular.ttf


